### ISSUE TITLE
region search doesn't work on chrX (but does work on others)

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/gnomad_browser#100]
Searching for  X:3311244

goes to  http://gnomad-beta.broadinstitute.org/region/X-3311244-3311244

which gets stuck @ 'loading'

![image](https://user-images.githubusercontent.com/6240170/35546420-2afee3b2-0542-11e8-8b52-ec55dff1f203.png)

**Comment by nawatts** [comment]
This seems like it could be an issue with an Elasticsearch mapping similar to #108.

**Comment by nawatts** [comment]
Issue moved to macarthur-lab/gnomadjs#54
