### ISSUE TITLE
Concern about accuracy of regional missense constraint data

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/gnomad_browser#108]
I really like the regional constraint bar on ExAC view in the beta browser. CDKL5 is my go to example for regional missense constraint but it doesn't have the regional constraint marked while other genes do. Any idea why it's missing? 

![image](https://user-images.githubusercontent.com/10407888/37845216-5675585a-2ea0-11e8-8eba-a12aa130863c.png)

![image](https://user-images.githubusercontent.com/10407888/37845244-650167ce-2ea0-11e8-8530-cbdfc1348f14.png)

**Comment by mattsolo1** [comment]
Nice catch!
