### ISSUE TITLE
Chr1 VCF truncated in liftover_grch38

### ISSUE THREAD

**Issue by donnawerling** [macarthur-lab/gnomad_browser#110]
Lifted-over chromosome 1 VCF file at gs://gnomad-public/release/2.0.2/vcf/genomes/liftover_grch38/ appears to be truncated. Running `bcftools view` or other bcftools command returns the following warning:
"[W::bgzf_read_block] EOF marker is absent. The input is probably truncated"

File size supports this, as the chromosome 1 file is far smaller than chromosome 2, etc. Possible problem with liftover, or data upload?

**Comment by bw2** [comment]
Thanks for reporting this. 
Indeed, the liftover job didn't complete.  I thought I checked this, but somehow missed chr1. 
I'll be re-uploading the chr1 file after liftover finishes running. 
(Also, I've double-checked that the other chromosomes don't have this issue)

**Comment by bw2** [comment]
I've updated the chr1 vcf, tbi and log files.

For example, this should work now:
```
tabix http://storage.googleapis.com/gnomad-public/release/2.0.2/vcf/genomes/liftover_grch38/gnomad.genomes.r2.0.2.sites.chr1.liftover.b38.vcf.gz 1:12345-54321 | wc -l
```
