### ISSUE TITLE
search by position

### ISSUE THREAD

**Issue by SamGLZ** [macarthur-lab/gnomad_browser#111]
Is there any chance that I can determine how many results I can see in the search page when I search by position? If I use a position of A nucleotide to search the information now, the result of this nucleotide will show up but the variants around it are missing, which could be seen in the old version.

Thank you!

**Comment by nawatts** [comment]
Searching by position (for example: https://gnomad.broadinstitute.org/region/1-55516888) shows a 40 base pair window around the specified position. Any variants within that window will be displayed.
