### ISSUE TITLE
Discrepancy between variant track and table

### ISSUE THREAD

**Issue by jamesware** [macarthur-lab/gnomad_browser#112]
Hi Matt,
When browsing RBM20 http://gnomad-beta.broadinstitute.org/gene/RBM20 , I filtered to show LoF variants only, and noticed when I scrolled to the bottom of the variant table the most distal variants on the graphic were not visible in the table: i.e. there are variants plotted in the "LoF" track that are never visible in the "Viewing in table" track.

**Comment by nawatts** [comment]
Hi @jamesware,

A fix for this issue has been merged and will be available with the next update of gnomad-beta.broadinstitute.org.
