### ISSUE TITLE
Not all exons represented in transcript models

### ISSUE THREAD

**Issue by jamesware** [macarthur-lab/gnomad_browser#119]
Hi Matt,

I'm not sure why not all exons are visible in the transcript cartoon.

e.g. http://gnomad-beta.broadinstitute.org/gene/LAMP2  has 3 main isoforms  (ENSTs ending 600,639 & 335).  These have 3 different terminal exons (exon 9 in each case), but otherwise are identical.
The terminal exon is visible for the first of these, but not the other 2.

http://ftp.ebi.ac.uk/pub/databases/lrgex/LRG_749.xml  has nice image to show what I mean.

Is this because the exons are not in the canonical transcript perhaps?

**Comment by bw2** [comment]
Hi James, 
Thanks for reporting this. We see the issue and are working on it. 

We're currently moving gnomad-beta issues to https://github.com/macarthur-lab/gnomadjs/issues/30
