### ISSUE TITLE
RYR1

### ISSUE THREAD

**Issue by EngleGC** [macarthur-lab/gnomad_browser#120]
Gene information does not come up for multiple users in lab when typing RYR1 into search field.

**Comment by nawatts** [comment]
Hi @EngleGC 

We have a beta version of the browser that will be released soon and has this gene working.

http://gnomad-beta.broadinstitute.org/gene/RYR1

We'd appreciate any feedback on this new version.

**Comment by EngleGC** [comment]
Thanks so very much!

Best Regards,
Brenda

Brenda J. Barry, MS, CGC
Licensed Genetic Counselor and Research Coordinator
Engle Research Laboratory-Boston Children’s Hospital
Email:  brenda.barry2@childrens.harvard.edu<mailto:brenda.barry2@childrens.harvard.edu>
Phone: 617-919-2168 | Fax: 617-730-4834
Mailing Address:  300 Longwood Avenue | BCH 3149-Neurology | CLS 14076-Engle Lab | Boston, MA 02115
Street Address (FedEx, couriers):  3 Blackfan Street | | BCH 3149-Neurology | CLS 14076-Engle Lab | Boston, MA 02115
**My emails sent with #secure# in the subject line are encrypted to protect your privacy or that of your patients and our research subjects.**
