### ISSUE TITLE
Problems Loading Gene: SYNE1

### ISSUE THREAD

**Issue by kjngo** [macarthur-lab/gnomad_browser#121]
Hi ,

I am having issues loading the SYNE1 page from gnomAD:
http://gnomad.broadinstitute.org/gene/ENSG00000131018

I get the following error from my Chrome browser:
![image](https://user-images.githubusercontent.com/39168305/39885168-c5f1bca8-5440-11e8-9ef2-763cb990d83b.png)

I'm able to load other genes just fine from gnomAD. 

Thanks!
Kathie

**Comment by nawatts** [comment]
Hi Kathie,

We have a beta version of the browser that will be released soon and has this gene working.

http://gnomad-beta.broadinstitute.org/gene/SYNE1

**Comment by kjngo** [comment]
Hi ,

Thanks for sharing the beta version of the page. It looks very nice with a lot of features, however I am having a hard time turning on the "All" variants function. Is this something on my end? 

![image](https://user-images.githubusercontent.com/39168305/39890979-5060ece6-5451-11e8-8b75-53b9cb944696.png)

Thanks!
Kathie

**Comment by nawatts** [comment]
Due to performance concerns around rendering many variants, some filters are not available for large genes.

I filed https://github.com/macarthur-lab/gnomadjs/issues/31 to clarify when/why the filters are disabled.

**Comment by kjngo** [comment]
Hi Nick,

Yes, it would be helpful to have a tooltip or some "disabled" distinction to show that the "All" filter is disabled for large genes. 

Thanks!
Kathie
