### ISSUE TITLE
Missing dbSNP RS ID

### ISSUE THREAD

**Issue by lonphan** [macarthur-lab/gnomad_browser#128]
Hi, 

I'm following up with a user of dbSNP and ExAC for a question as to why some ExAC variants don't have RS ID.  For example this variant.
http://exac.broadinstitute.org/variant/22-46594255-G-A

dbSNP have released RS IDs for all GnomAD and ExAc variants in latest build 151.   For the variant above the RS ID is rs769784767.
https://www.ncbi.nlm.nih.gov/snp/rs769784767

Can ExAC browser be updated to include the new RS ID?  There's an API to get the matching RS ID.
Exac variant:  22-46594255-G-A
Converted to SPDI format:  NC_000022.10:46594255:G:A

curl -X GET --header "Accept: application/json" "https://api.ncbi.nlm.nih.gov/variation/v0/spdi/NC_000022.10%3A46594254%3AG%3AA/rsids"  

The complete list of corresponding chromosome accessions for GRCh37 (https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.25)

Otherwise,  please contact snp-admin@ncbi.nlm.nih.gov if you need help getting the complete list of RS IDs.

**Comment by nawatts** [comment]
We do not continuously update the dbSNP rsIDs displayed in the browser, so there will be some differences the databases and dbSNP depending on versions been used. ExAC was annotated with dbSNP version 141.

See the ["Why is this variant linked to the wrong dbSNP rsID?" FAQ entry](https://gnomad.broadinstitute.org/faq#why-is-this-variant-linked-to-the-wrong-dbsnp-rsid).
