### ISSUE TITLE
file for cnv  are missing 

### ISSUE THREAD

**Issue by aurelBZH** [macarthur-lab/gnomad_browser#129]
Hi, 
Thank you for your work on gnomad and gnomad browser. Im trying to install gnomad on my pc.  The four files are missing :   
forweb_cleaned_exac_r03_march16_z_data_pLI_CNV-final.txt.gz
MNPs_NotFiltered_ForBrowserRelease.txt.gz
exac-gencode-exon.cnt.final.pop3
exac-final-cnvs.gene.rank

I have watched on the google cloud and i can't find them.

Thanks for your help. 

Aurélien Béliard

**Comment by nawatts** [comment]
These files are available at:

* gs://gnomad-public/legacy/exac_browser/forweb_cleaned_exac_r03_march16_z_data_pLI_CNV-final.txt.gz
* gs://gnomad-public/legacy/exac_browser/MNPs_NotFiltered_ForBrowserRelease.txt.gz
* gs://gnomad-public/legacy/exac_browser/exac-gencode-exon.cnt.final.pop3
* gs://gnomad-public/legacy/exac_browser/exac-final-cnvs.gene.rank

**Comment by aurelBZH** [comment]
thanks for your help
