### ISSUE TITLE
SNP table for STAT1 canonical transcript != ENST displayed

### ISSUE THREAD

**Issue by joegeorgeson** [macarthur-lab/gnomad_browser#130]
I happened to notice that the canonical transcript for STAT1

http://gnomad.broadinstitute.org/gene/ENSG00000115415

Does not match the ENST which is written as canonical, but does if accessed another way

http://gnomad.broadinstitute.org/transcript/ENST00000361099

I only noticed because I linked the table to other databases via NM_007315~ENST00000361099

**Comment by nawatts** [comment]
In the current browser, both https://gnomad.broadinstitute.org/gene/ENSG00000115415 and https://gnomad.broadinstitute.org/gene/ENSG00000115415/transcript/ENST00000361099 identify ENST00000361099 as the canonical transcript.
