### ISSUE TITLE
hemizygous column disappears in transcript view 

### ISSUE THREAD

**Issue by rmathis2** [macarthur-lab/gnomad_browser#132]
I've noticed a problem:
If you look at an X-linked or Y-linked gene in the browser, there is, appropriately, a column for hemizygocity (for males with only one of these chromosomes). 

However, that disappears if you move into the view for any transcript. 
This example can be seen with the Y chromosome gene SRY:
[gene view has Hemizygous](http://gnomad.broadinstitute.org/gene/ENSG00000184895)
[transcript view has (inappropriately) homozygous: ](http://gnomad.broadinstitute.org/transcript/ENST00000383070)

Similarly, you can see this with the X chromosome gene PORCN:
[gene view has Hemizygous](http://gnomad.broadinstitute.org/gene/ENSG00000102312)
[transcript view loses Hemizygous column](http://gnomad.broadinstitute.org/transcript/ENST00000326194)

Thanks.

**Comment by nawatts** [comment]
These columns are displayed correctly in the current version of the browser.
