### ISSUE TITLE
Get allele counts/frequencies per ethnicity and sex in autosomes

### ISSUE THREAD

**Issue by mvysotskiy** [macarthur-lab/gnomad_browser#134]
We have the VCFs and we see that the X-chromosome variants have a field like AF_EAS_Male, which includes both sex and ethnicity, but the autosomes only have per-sex and per-ethnicity frequencies. We would be interested in seeing these combined statistic for the other chromosomes as well.

**Comment by gtiao** [comment]
We'll be releasing these as part of the upcoming 2.1 release, so look for these in the coming weeks!

**Comment by nawatts** [comment]
With the release of [gnomAD 2.1](https://macarthurlab.org/2018/10/17/gnomad-v2-1/), this information is available in the VCFs and in the browser.
