### ISSUE TITLE
CSV Table for a Particular Transcript Doesn't Download

### ISSUE THREAD

**Issue by redmoon6584** [macarthur-lab/gnomad_browser#135]
### What you did:
Was trying to download the table of variants to CSV (using the button) for ATM, Transcript: ENST00000278616 (62 coding exons) from both gnomAD ([](http://gnomad.broadinstitute.org/transcript/ENST00000278616)) and the beta browser ([](http://gnomad-beta.broadinstitute.org/transcript/ENST00000278616)),

### What happened:
I get a Failed - Network error when trying to download the file for that transcript.

**Comment by nawatts** [comment]
Exporting variants to CSV is working on https://gnomad.broadinstitute.org/gene/ENSG00000149311/transcript/ENST00000278616.
