### ISSUE TITLE
Cannot vist GnomAD new browser

### ISSUE THREAD

**Issue by dioncst** [macarthur-lab/gnomad_browser#138]
Cannot visit the website of http://gnomad.broadinstitute.org/, but I still could visit http://gnomad-old.broadinstitute.org/ the old one.

**Comment by mattsolo1** [comment]
Hi, what browser are you using?

**Comment by dioncst** [comment]
I have tried Chrome and safari

**Comment by dioncst** [comment]
> Hi, what browser are you using? (e.g. Chrome, Firefox, Internet explorer?)

I have tried Chrome, Safari, Firefox and IE. None of these works
