### ISSUE TITLE
bug in 'no coverage statement'

### ISSUE THREAD

**Issue by samesense** [macarthur-lab/gnomad_browser#28]
I have an hg19 variant (16-71026076-C-G) that is not present (but covered) in exac (http://exac.broadinstitute.org/variant/16-71026076-C-G), and not present / not covered in gnomAD (http://gnomad.broadinstitute.org/variant/16-71026076-C-G). Is exac not a subset of gnomAD? How can the position be covered in exac and not genomad?

This closest variant shows reads covering 71026076 (http://gnomad.broadinstitute.org/variant/16-71026065-C-A). I think your 'no coverage' statement has a bug. Here's a well covered non-variant location gives the same error: http://gnomad.broadinstitute.org/variant/2-198257009-C-A

**Comment by mattsolo1** [comment]
Thanks for pointing this out. Should be fixed now. 

http://gnomad.broadinstitute.org/variant/16-71026076-C-G
http://gnomad.broadinstitute.org/variant/2-198257009-C-A
