### ISSUE TITLE
Genome coverage missing in nonexonic regions

### ISSUE THREAD

**Issue by assaron** [macarthur-lab/gnomad_browser#29]
It seems there are some problems with genome coverage data/plots.

For example:
1. Open region http://gnomad.broadinstitute.org/region/1-55505224-55505224
2. Compare genome coverage graph and variants table. There are genomic variants but no genomic coverage.

Overall I wasn't able to find any region that has genome coverage and no exom coverage.

**Comment by mattsolo1** [comment]
At the moment, WGS coverage is displayed only for exonic regions in the browser. We are currently working on adding genome coverage for non-exonic regions to the browser. In the meantime, a message has been added to the region page to explain this https://github.com/macarthur-lab/gnomad_browser/commit/cf7eaa976608cd58ef170a69bd70f91d3f4ec21d.

**Comment by nawatts** [comment]
In the current version of the browser, genome coverage is shown for non-exonic regions.
