### ISSUE TITLE
Meaning of Filter value message

### ISSUE THREAD

**Issue by JimScottM** [macarthur-lab/gnomad_browser#30]
IN the ExAC browser - GRIN2A variant p.Ser1415Leu the Filter designation is PASS.  This same variant (GRIN2A p.Ser1415Leu) in gnomAD shows the exome button "ghosted" with this message when scrolling over the button: "This variant found in ExAC dataset w/filter value VQSRTrancheINDEL98.00to98.50"  

Why is there a difference between the two databases and what does this message tell me.

**Comment by mattsolo1** [comment]
Filters have explanations now https://github.com/macarthur-lab/gnomad_browser/commit/1861f25da32ad8c298aa587400f6c456133eba04. Also see: https://macarthurlab.org/2017/02/27/the-genome-aggregation-database-gnomad/
