### ISSUE TITLE
Please add c. HGVS nomenclature to variants

### ISSUE THREAD

**Issue by kalon33** [macarthur-lab/gnomad_browser#32]
Could you please add the c. HGVS nomenclature to variants listed in gnomAD? Most people studying variants work with c. names and that make it harder to find them in gnomAD.

Thanks for implementing this.

**Comment by mattsolo1** [comment]
Hi there, thanks for the suggestion. Currently, the consequence HGVS in the variant table is set to `HGVSc` if the `major consequence` is one of `('splice_donor_variant', 'splice_acceptor_variant', 'splice_region_variant')`. Anything else is `HGVSp`. This is behavior we believe most people like to see, especially for protein coding variants. You're welcome to dig into the VCF to learn about the c. HGVS annotations.

**Comment by kalon33** [comment]
Unfortunately, most disease databases use c. HGVS nomenclature too or only (BRCA Exchange, BRCAShare, ClinVar...) that would be useful for people disease oriented where variants are reported to patients and clinicians as c. annotations. 


----- Mail original -----

De: "Matthew Solomonson" <notifications@github.com> 
À: "macarthur-lab/gnomad_browser" <gnomad_browser@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 14 Mars 2017 17:14:37 
Objet: Re: [macarthur-lab/gnomad_browser] Please add c. HGVS nomenclature to variants (#32) 



Hi there, thanks for the suggestion. Currently, the consequence HGVS in the variant table is set to HGVSc if the major consequence is one of ('splice_donor_variant', 'splice_acceptor_variant', 'splice_region_variant') . Anything else is HGVSp . This is behavior we believe most people like to see, especially for protein coding variants. You're welcome to dig into the VCF to learn about the c. HGVS annotations.

**Comment by kalon33** [comment]
@mattsolo1 most people, probably not from the diagnosis/clinician world (see previous comment) that also account lots of people... Is that so complicated to add one more field for it (and being able to query it)?
