### ISSUE TITLE
IGV tracks on variant pages don't load

### ISSUE THREAD

**Issue by beaugunderson** [macarthur-lab/gnomad_browser#33]
The exome in the IGV.js viewer does not load; there are JS errors in the console.

Here's one example: http://gnomad.broadinstitute.org/variant/11-121008357-T-A

![screenshot of IGV.js tracks](https://i.imgur.com/NWsoBb5.png)

![screenshot of JS console](https://i.imgur.com/hDuGK2s.png)

**Comment by mattsolo1** [comment]
Is this happening for all variants?

**Comment by beaugunderson** [comment]
@mattsolo1 also happens with the [one linked to from the front page](http://gnomad.broadinstitute.org/variant/1-55516888-G-GA) so seems like that's a yes :)

**Comment by mattsolo1** [comment]
Switched to locally-hosted hg19 fasta https://github.com/macarthur-lab/gnomad_browser/commit/78953a0db71e419d0c8d5e6483d5493b18dbbc98
