### ISSUE TITLE
RSID handling

### ISSUE THREAD

**Issue by mattsolo1** [macarthur-lab/gnomad_browser#36]
If someone searches for a variant by RSID that is in our dbSNP database, but the variant doesn’t exist in gnomad, it returns a region page along with a message saying something like “According to dbSNP, a variant with RSID: <id > is located in this region but we could not find the variant in gnomAD”. And if the RSID does not exist at all in dbSNP, we wouldn’t show any region page and the message would be “A variant with RSID:<id> could not be found in dbSNP.

**Comment by nawatts** [comment]
Issue moved to macarthur-lab/gnomadjs#38
