### ISSUE TITLE
Cannot Export Table to CSV

### ISSUE THREAD

**Issue by ifrahs** [macarthur-lab/gnomad_browser#39]
Hi. Lately I've found that I can't export tables to CSV anymore on gnomAD. The download always fails no matter what browser I use. I can export the CSV from ExAC though which is what made me think it might be an error of the gnomAD website. The specific genes I was trying to export were COL7A1 and FLG. 

Also, when I try to export the CSV, the file is simply called "download" and the file type is listed as "All Files".  Whereas on ExAC, there's a file name like "exac_ENSG00000133710_2017_02_22_00_13_51" and the file type is "Microsoft Excel Comma Separated Values File". 

I hope this can be fixed soon. 

Ifrah

**Comment by mattsolo1** [comment]
Hi for some reason, our CSV export function is having trouble with big genes such as COL7A1. I tried to figure it out but no luck -- handling big genes is something we're actively working on improving in the gnomad browser. For now, you may want try exporting by smaller regions or download the VCF.

**Comment by nawatts** [comment]
Exporting the table is working for COL7A1 in the beta version of the new gnomAD browser. Exporting the table works for FLG works if the table is filtered to "Missense + LoF" or "LoF".

http://gnomad-beta.broadinstitute.org/gene/COL7A1
http://gnomad-beta.broadinstitute.org/gene/FLG
