### ISSUE TITLE
add option to show/hide deep-intronic variants for gnomad

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/gnomad_browser#4]
add server-side parameter`include_deep_intronic`  to `gene_page` and `get_gene_page_content` methods (it should be false by default) so that deep intron variants from gnomad aren't loaded unless requested.

**Comment by mattsolo1** [comment]
This was implemented at https://github.com/macarthur-lab/gnomad_browser/blame/master/lookups.py#L341
