### ISSUE TITLE
DBsnp search not working

### ISSUE THREAD

**Issue by Steven-N-Hart** [macarthur-lab/gnomad_browser#40]
Using the example provided on the homepage, this query works fine:
`http://gnomad.broadinstitute.org/variant/1-55516888-G-GA`
However, if you search for the rsID that corresponds to that variant:
`http://gnomad.broadinstitute.org/dbsnp/rs778104784` you don't get a result.  The main section just says "Loading Variant"

**Comment by pjvandehaar** [comment]
If you put 
```
javascript:window.alert(_.union(_.flatten(window.variants.map(d=>"http://gnomad.broadinstitute.org/variant/"+d.orig_alt_alleles))))
```
in your address bar and hit enter, it'll give you the URLs of the pages you wanted.

**Comment by mattsolo1** [comment]
Fixed now, gnomad.broadinstitute.org/dbsnp/rs778104784
