### ISSUE TITLE
Y chromosome Population Frequency table missing a column header

### ISSUE THREAD

**Issue by tsneddon** [macarthur-lab/gnomad_browser#41]
Hi:

It looks like there is an extra column, or else a missing column header, for variants on chrY genes.
Thanks,

Tam

**Comment by nawatts** [comment]
For an example, see http://gnomad.broadinstitute.org/variant/Y-2654979-G-C

<img width="627" alt="screen shot 2018-05-11 at 11 23 09 am" src="https://user-images.githubusercontent.com/1156625/39932298-c5b7338a-550d-11e8-97ba-a4418f4bf4fb.png">
