### ISSUE TITLE
CNV file download

### ISSUE THREAD

**Issue by jpdna** [macarthur-lab/gnomad_browser#43]
Hi, 

Thanks for this great resource in ExAC/gnomAD!

At NIH/NHGRI we want to set up a local clone of gnomAD, and be able to load our own cohort data.  We did that with an older version of ExAC earlier, but now we find two files for which we are unsure if we need to generate locally as we try to move from ExAC to gnomAD as a model.

Can you tell us more about the two files?
`exac-gencode-exon.cnt.final.pop3`
https://github.com/macarthur-lab/gnomad_browser/blob/master/exac.py#L98
and
`exac-final-cnvs.gene.rank`
https://github.com/macarthur-lab/gnomad_browser/blob/master/exac.py#L99

Could you make these available? as you do the other files at:
https://personal.broadinstitute.org/konradk/exac_browser/

That would be useful for our clone effort and as an example.

And can you comment on whether these cnv files are reference data applicable to other cohorts (as are dbNSFP ref data), or if we need to generate our own version of these based on our own cohort data?

Thanks,
Justin Paschall

**Comment by jpdna** [comment]
This file:
https://github.com/macarthur-lab/gnomad_browser/blob/master/exac.py#L96
also we may need help  to know where to download it from:
forweb_cleaned_exac_r03_march16_z_data_pLI_CNV-final.txt.gz

**Comment by mattsolo1** [comment]
Hey, sorry about the late response. You can find the files at https://console.cloud.google.com/storage/browser/gnomad-public/release-170228/browser_reference_data/

I believe the CNV data is specific to your cohort. @konradjk how would they generate this?

**Comment by aurelBZH** [comment]
Hi i also need  this file and the google cloud directory seem to be empty for me.

**Comment by nawatts** [comment]
These files are available at:

* gs://gnomad-public/legacy/exac_browser/exac-final-cnvs.gene.rank
* gs://gnomad-public/legacy/exac_browser/exac-gencode-exon.cnt.final.pop3

**Comment by Kebulser** [comment]
I have been able to obtain the files in question by following the google bucket link from exac.broadinstitute.org/downloads to the gnomad repository;

https://console.cloud.google.com/storage/browser/gnomad-public/legacy/exacv1_downloads?project=broad-mpg-gnomad&organizationId=548622027621

a subset of which are the exac files ( /legacy/exac_browser/ ) including ones that as far as I can tell are missing both from exac_browser.tar.gz and the ftp repository.
