### ISSUE TITLE
(some) indels do not follow vcf standard

### ISSUE THREAD

**Issue by my-umd** [macarthur-lab/gnomad_browser#44]
E.g., for the exom set:
1       324677  rs764720704     ACCTCACCAGGCCCAGCTCATGCTTCTTTGCAG       A,TCCTCACCAGGCCCAGCTCATGCTTCTTTGCAG

vcf standard requires repeating of the common leading base.  But the example (2nd variant) doesn't.

**Comment by janrehker** [comment]
Good catch!
If I get the docs for the vcf standard right, the second one should actually be a separate variant on 1 324676

**Comment by nawatts** [comment]
This repository is no longer maintained. If this is still an issue in VCFs for the current gnomAD release, please file an issue on [broadinstitute/gnomad_methods](https://github.com/broadinstitute/gnomad_methods).
