### ISSUE TITLE
VCFs are only normalised in respect of one alt allele

### ISSUE THREAD

**Issue by pdl** [macarthur-lab/gnomad_browser#47]
Consider the gnomAD genomes entry:

    21 10910129 . CAAAT TAAAT,C,CAAT

This entry represents three variants. If they appeared as separate entries, the parsimonious left-aligned normalisation would be C/T, CAAAT/C and CA/C, which is how they are represented on the gnomAD website. Incidentally, this makes it more difficult for us to link back to gnomAD, because we would need to normalise each variant first.

Is there any rationale behind this consolidation?

**Comment by mattsolo1** [comment]
https://github.com/macarthur-lab/gnomad_browser/issues/48
