### ISSUE TITLE
Non-TCGA version

### ISSUE THREAD

**Issue by gormleymp** [macarthur-lab/gnomad_browser#51]
Exac version 1.0 has a non-TCGA subset available for download.   Will a non-TCGA version be available for Gnomad?   Is there a timeline for when this resource will be available?

**Comment by alexcharney** [comment]
Similarly, wondering if a non-psych version of Gnomad is coming

**Comment by janrehker** [comment]
Following up to the first question:
Is there an absolute number of TCGA samples available which were included in the db?

**Comment by janrehker** [comment]
Following up to the first question:
Are there TCGA samples in the gnomAD genome db?

**Comment by sayonidas03** [comment]
Hi, just a followup to the previous questions in this thread:
How many TCGA samples are present in the gnomAD exome db? 
and 
Is there a non-TCGA version of gnomAD available for download?

Thanks in advance.

**Comment by nawatts** [comment]
[gnomAD 2.1](https://macarthurlab.org/2018/10/17/gnomad-v2-1/) includes information on non-cancer and non-neuro subsets. The number of samples in each subset can be found on the [FAQ page](https://gnomad.broadinstitute.org/faq).
