### ISSUE TITLE
Flagging genes with pseudogenes

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/gnomad_browser#52]
Place a warning flag on PRSS1 that there is a pseudogene that affects variant calls of these gene. We may want to expand this to cover other genes where this is a frequent issue. PMS2 has also come up. We could ask LMM (Heidi or Matt Lebo) for other genes you might want to flag.

**Comment by nawatts** [comment]
Issue moved to macarthur-lab/gnomadjs#40
