### ISSUE TITLE
caching - missing function get_gene_page_content

### ISSUE THREAD

**Issue by ameynert** [macarthur-lab/gnomad_browser#56]
`-bash-4.1$ python manage.py create_cache`
`global name 'get_gene_page_content' is not defined`

Can't find this function anywhere in the code base.

**Comment by nawatts** [comment]
Hi @ameynert,

We're no longer using this code internally, and thus have no plans to fix.

You can find the implementation of the `get_gene_page_content` function here:
https://github.com/konradjk/exac_browser/blob/a212465c5b75752abe8990cf6aa581295835ab58/exac.py#L664-L703
