### ISSUE TITLE
http:// (...)/gnomad.genomes.r2.0.1.sites.1.vcf.gz returns a XML doc 'The specified key does not exist'

### ISSUE THREAD

**Issue by lindenb** [macarthur-lab/gnomad_browser#59]
Hi,
FYI: 

I'm trying to download: https://storage.googleapis.com/gnomad-public/release-170228/vcf/genomes/gnomad.genomes.r2.0.1.sites.1.vcf.gz

May be it's a temporary problem, but  for now my browser just returns a XML document:

`<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>`

Best,
PL

**Comment by jsh2134** [comment]
It looks like the URLs changed but the downloads page was not updated.
 
change`release-170228` to `release/2.0.1` in all the URLs.

example:
https://storage.googleapis.com/gnomad-public/release/2.0.1/vcf/genomes/gnomad.genomes.r2.0.1.sites.1.vcf.gz

**Comment by mattsolo1** [comment]
Fixed
