### ISSUE TITLE
ClinVar links for multi-allelic or INDEL variants seem to be incorrect

### ISSUE THREAD

**Issue by niab** [macarthur-lab/gnomad_browser#62]
ClinVar links for multi-allelic or INDEL variants seem to be incorrect.

For example, here are links to the same Cystic Fibrosis variant 7-117199644-ATCT-A (p.Phe508delPhe) in ExAC and gnomAD:

1) ExAC: [7-117199644-ATCT-A](http://exac.broadinstitute.org/variant/7-117199644-ATCT-A) 
2) gnomAD: [7-117199644-ATCT-A](http://gnomad.broadinstitute.org/variant/7-117199644-ATCT-A)

However, this variant has different rs numbers in ExAC (rs113993960) and gnomAD (rs1801178). It seems that gnomAD rs number is incorrect as it links to a wrong [ClinVar Page](https://www.ncbi.nlm.nih.gov/clinvar/variation/188863/) with a different variant (p.Ile507Val).

So that's a problem with rs number linkage, but there is also a problem with chrom position linkage. It seems that ClinVar uses different annotation for indels, so you can't search ClinVar using chrom and position from ExAC or gnomAD. However, that's what some links in ExAC and gnomAD are trying to do if there is no rs number. For example this variant 3-14199738-GCA-G (p.Val548AlafsTer25) exists in both ExAC and gnomAD:

1) ExAC: [3-14199738-GCA-G](http://exac.broadinstitute.org/variant/3-14199738-GCA-G)
2) gnomAD: [3-14199738-GCA-G](http://gnomad.broadinstitute.org/variant/3-14199738-GCA-G)

However, according to their link (which searches for variant using chrom and position) this variant [does not exist in ClinVar](https://www.ncbi.nlm.nih.gov/clinvar?term=(3%5BChromosome%5D)%20AND%2014199738%5BBase%20Position%20for%20Assembly%20GRCh37%5D)

Whereas in fact, it [does exist](https://www.ncbi.nlm.nih.gov/clinvar/variation/262/), but you need to search with pos + 1:

However, increasing ExAC or gnomAD chrom position by one might not work for some variants. For example, Cystic Fibrosis variant 7-117199644-ATCT-A (p.Phe508delPhe), for some reason is stored in ClinVar as:

chrom: 7   
start: 117199646   
end: 117199648   
ref: CTT  
alt: -

So in this case ClinVar uses +2 chrom position, as even Ref nucleotides are different (ExAC and gnomAD: TCT, ClinVar: CTT).

**Comment by bw2** [comment]
I've also noticed incorrect clinvar links recently. The clinvar VCF has an allele id field for each variant. Using the allele id in links like allele id 195141 => 
https://www.ncbi.nlm.nih.gov/clinvar?term=195141%5BAlleleID%5D
should fix this.

**Comment by nawatts** [comment]
This should be resolved in the browser with broadinstitute/gnomad-browser#421.
