### ISSUE TITLE
wrong rs number 

### ISSUE THREAD

**Issue by HuifangYAN** [macarthur-lab/gnomad_browser#63]
There seem to be some wrong rs numver~
such as
"Variant: 1:26608835 ACCGGGACCGGGACTGGG / A       
 dbSNP rs61775087"
 The correct rs number should be rs757094832

"Variant: 1:26608865 ACC / A
  dbSNPrs751097385"
 The correct rs number should be rs764852231

"Variant: 5:139422564 CGCT / C
 dbSNPrs557310960"
 The correct rs number should be rs772610870

"Variant: 5:138725509 CCAG / C
dbSNPrs748501256"
 The correct rs number should be rs774544239

**Comment by niab** [comment]
This seems relevant to the issue "ClinVar links for multi-allelic or INDEL variants seem to be incorrect" which I've created some time ago, as all listed variants are INDELs.

**Comment by nawatts** [comment]
I think this is resolved in gnomAD v3.1 (broadinstitute/gnomad_qc#77). In previous releases, rsIDs were matched to gnomAD variants based on locus only.

Also, see the ["Why is this variant linked to the wrong dbSNP rsID?" FAQ entry](https://gnomad.broadinstitute.org/faq#why-is-this-variant-linked-to-the-wrong-dbsnp-rsid).
