### ISSUE TITLE
how to unzip 'gnomad.exomes.r2.0.0.sites.vcf.bgz' to VCF file

### ISSUE THREAD

**Issue by zhangpeng1202** [macarthur-lab/gnomad_browser#65]
Dear gnomAD team,

I wish to work with the information in gnomAD Exome VCF file, however I did not manage to open or unzip the file 'gnomad.exomes.r2.0.0.sites.vcf.bgz'.
Look forward your kind and helpful advice.

Best Regards,
Peng

**Comment by nawatts** [comment]
Hi @waynezhangnus,

Try one of:

```
gunzip -c gnomad.exomes.r2.0.0.sites.vcf.bgz > gnomad.exomes.r2.0.0.sites.vcf
```
or
```
gzcat gnomad.exomes.r2.0.0.sites.vcf.bgz > gnomad.exomes.r2.0.0.sites.vcf
```
