### ISSUE TITLE
Disable All and Missense + LoF buttons on TTN

### ISSUE THREAD

**Issue by konradjk** [macarthur-lab/gnomad_browser#69]

**Comment by konradjk** [comment]
Probably also on large region pages

**Comment by nawatts** [comment]
These filters are disabled for large genes.

https://github.com/macarthur-lab/gnomadjs/blob/3816f2be5f10e4d2ae6e8430ca19695f3637e614/projects/gnomad/src/Settings.js#L55-L112

Related to https://github.com/macarthur-lab/gnomadjs/issues/31
