### ISSUE TITLE
Add documentation to explain important parts of the gene page

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/gnomad_browser#70]
![image](https://user-images.githubusercontent.com/6240170/33623410-d8a02576-d9be-11e7-987f-2a5de231b457.png)

**Comment by bw2** [comment]
Comes up when clicking this question mark: 
![image](https://user-images.githubusercontent.com/6240170/33623514-406411d6-d9bf-11e7-947e-cd93a174f80d.png)

**Comment by nawatts** [comment]
Issue moved to macarthur-lab/gnomadjs#44
