### ISSUE TITLE
"Gene not found" searches should have informative page rather than javascript error

### ISSUE THREAD

**Issue by mattsolo1** [macarthur-lab/gnomad_browser#74]

**Comment by konradjk** [comment]
e.g. http://35.184.206.249/gene/MLL2

See also https://github.com/konradjk/exac_browser/issues/157

**Comment by konradjk** [comment]
An ambiguity page would be ideal here, but I appreciate that that takes a bit more effort

**Comment by nawatts** [comment]
Issue moved to macarthur-lab/gnomadjs#46
