### ISSUE TITLE
Non-cannonical transcript marker missing in new browser

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/gnomad_browser#80]
In the original flavor ExAC and gnomAD browsers, if a variant is in the non-cannonical transcript, it has a cross next to it which is helpful in identifying LOF variants that may not be real LOF (given the worst annotation is shown). I find this to be a helpful mark.

**Comment by nawatts** [comment]
Issue moved to macarthur-lab/gnomadjs#50
