### ISSUE TITLE
Problematic use of Number=G in INFO records

### ISSUE THREAD

**Issue by bioinformed** [macarthur-lab/gnomad_browser#85]
Please see this issue https://github.com/samtools/hts-specs/issues/272, which was opened as a result of https://github.com/pysam-developers/pysam/issues/593.

**Comment by konradjk** [comment]
As this is a spec issue rather than gnomAD, I'm going to close this for now. Happy to re-open if and when the spec is adjusted, or a general solution is adopted (see https://github.com/samtools/hts-specs/issues/272#issuecomment-354844529)
