### ISSUE TITLE
No module named ext.script

### ISSUE THREAD

**Issue by AKILLIMUSTAFA** [macarthur-lab/gnomad_browser#87]
### I get the error for ubuntu 14.04 and ubuntu 16.04.

> python manage.py load_db

the above code gives this error for Python 2.7.12:

> Traceback (most recent call last):
>   File "manage.py", line 1, in <module>
>     from flask.ext.script import Manager
> ImportError: No module named ext.script

the above code gives this error for Python 3.5.2:

> Traceback (most recent call last):
>   File "manage.py", line 1, in <module>
>     from flask.ext.script import Manager
> ImportError: No module named 'flask'

# My Solution:
I changed this lines:

**in manage.py line 1:**

> from flask.ext.script import Manager

to

> from flask_script import Manager

**Comment by nawatts** [comment]
This repository is no longer being maintained. Development of the gnomAD browser has moved to [broadinstitute/gnomad-browser](https://github.com/broadinstitute/gnomad-browser).
