### ISSUE TITLE
Speed improvements

### ISSUE THREAD

**Issue by rowlandm** [macarthur-lab/gnomad_browser#89]
Hi there,

Thought I would put a comment here about the speed as I'm from Australia. 

Even though it's only 1MB download with 35 requests for http://gnomad-beta.broadinstitute.org/gene/PCSK9 - it takes ~9-10 seconds to load.

The genepage.js is actually the biggest file 381KB (it's minified but doesn't have the .min.js extension) but  it's not on a CDN. 

gnomad.js isn't minified or on a CDN.

Hope that helps...

**Comment by mattsolo1** [comment]
Thanks! I'll see what I can do to optimize this

**Comment by niab** [comment]
I would suggest to remove hidden columns processing in exac.js "update_variants" function, like population frequencies etc (i.e. comment out everything which is not visible and currently not used). I did it with a local version of gnomAD browser and it helped a lot, this function execution time on CFTR page dropped from ~15,1 sec to ~5.6 sec.

**Comment by nawatts** [comment]
Issue moved to macarthur-lab/gnomadjs#59
