### ISSUE TITLE
Suggestion: bring variant to front of "viewing in table" display when highlighted (or clicked) in table

### ISSUE THREAD

**Issue by mikegloudemans** [macarthur-lab/gnomad_browser#91]
Great new site! I love the visualization of all the known variants as ovals, and the ability to see which ones you're currently viewing in the table.

Right now it's still difficult for me to tell which variant in the table corresponds to which one in the visual display. I would suggest:
1) Bringing the variant to the front of the "viewing in table" display when you mouse over it in the table
2) Allowing user to select a variant in the table and have it stay selected once you move your mouse off of it
3) Allowing user to select a variant in the visualization and have it highlighted in the table after that

**Comment by nawatts** [comment]
Issue moved to macarthur-lab/gnomadjs#35
