### ISSUE TITLE
Stuck on "Loading..."

### ISSUE THREAD

**Issue by sds02** [macarthur-lab/gnomad_browser#92]
When I tried looking for ARID1B, BRCA1 or any gene for that matter, it got stuck. Says "Loading....". I tried Chrome and Safari. I then disconnected from the wifi of my building and connected to hotspot from my phone and it started working! My concern is that I have never had such issues with gnomAD (the original version) while using the wifi from my building so I don't know what's happening with the new version!

**Comment by mattsolo1** [comment]
Hello, I think we've addressed this issue. Would you mind trying again?

**Comment by sds02** [comment]
Hi! So, I tried again and it's still stuck on "Loading...". Checked my wifi connection and all websites including the old gnomad browser are working just fine.

**Comment by mattsolo1** [comment]
Thanks for trying it out again! Would you mind opening the developer tools console in your browser and taking a screenshot of what you see? For example in chrome, this is View > Developer > Javascript console

**Comment by nawatts** [comment]
Issue moved to macarthur-lab/gnomadjs#52
