### ISSUE TITLE
Add support for IE

### ISSUE THREAD

**Issue by mattsolo1** [macarthur-lab/gnomad_browser#94]
When searching gene in IE, the page loads fast but simply says "hello" at the top, otherwise blank.

**Comment by mattsolo1** [comment]
Support for internet explorer 11 added, however still an issue with the variant table search bar I'm working through. IE10 should be able to load the page however has layout issues due to partial support for flexbox see https://caniuse.com/#search=flex.

Thinking about how to support some of these old internet explorer versions 6 - 10. May be able to offer a very limited gene page.

**Comment by bw2** [comment]
Matt fixed this.
