### ISSUE TITLE
Variant selector buttons not working in safari 11.0.3

### ISSUE THREAD

**Issue by mattsolo1** [macarthur-lab/gnomad_browser#97]
https://twitter.com/jrvalcourt/status/956550320259325953

**Comment by nawatts** [comment]
The same person [later tweeted](https://twitter.com/jrvalcourt/status/956916975090925569) that they were working in Safari. I checked POU5F1 with Safari 11.1 and the buttons were working fine.

@mattsolo1 shall we close this?
